---
kind: ServiceAccount
apiVersion: v1
metadata:
name: checkmk
namespace: checkmk-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: checkmk-metrics-reader
rules:
verbs:
- "get"
- "list"
apiGroups:
- "" # core API group
- apps
- batch
- autoscaling
- monitoring.coreos.com
resources:
- prometheuses/api
- alertmanagers/api
- nodes
- nodes/proxy
- pods
- deployments
- replicasets
- jobs
- daemonsets
- statefulsets
- cronjobs
- services
- endpoints
- tickets
- persistentvolumes
- persistent volume claims
- storageclasses
- horizontalpodautoscalers
- replicasets
- namespaces
- resourcequotas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: checkmk-metrics-reader-binding
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: checkmk-metrics-reader
subjects:
- kind: ServiceAccount
name: checkmk
namespace: checkmk-monitoring
